Testimonials sections
Wuffes/wuffes-OS2.0 pull request #10
Opened 2024-08-06 16:34 UTC by Vadym-Mazurenko

### Asana Task link:

- [Asana Task](url)

### Demo links

- [Store](https://wuffes-store.myshopify.com/?preview_theme_id=130847998087)
- [Editor](https://admin.shopify.com/store/wuffes-store/themes/130847998087/editor?section=template--16238227357831__testimonials_full_width_kmk8m8&block=template--16238227357831__testimonials_full_width_kmk8m8__testimonials_slide_UGwK67)

### Checklist

- [ ] Tested on mobile
- [ ] Tested on desktop
- [ ] Requested review from QA (if applicable)

- [ ] Requested approval from 1 senior dev on Github and in Asana task
- [ ] Moved task to "QA" status in Asana

2024-08-12 11:03 UTC, alex-wuffes requested changes

2024-08-12 11:03 UTC, alex-wuffes commented on sections/testimonials.liquid
> +    calc(100vw - 10rem), 100vw
@Vadym-Mazurenko This image [doesn't look](https://tppr.me/jTq7dr) 100vw to me on mobile.

2024-08-12 11:03 UTC, alex-wuffes commented on sections/testimonials.liquid
> +    (min-width: {{ settings.page_width }}px) {{ settings.page_width | minus: 100 }}px, (min-width: 750px)
@Vadym-Mazurenko It's [not](https://tppr.me/bogUk6) 1100 px on desktop. Please, review this image sizes.

2024-08-13 16:00 UTC, Vadym-Mazurenko commented on assets/section-multicolumn.css
>  }
fixed

2024-08-13 16:00 UTC, Vadym-Mazurenko commented on assets/section-testimonials-full-width.css
> +.slide_content__heading {
fixed

2024-08-13 16:00 UTC, Vadym-Mazurenko commented on assets/section-testimonials-full-width.css
> +}
fixed

2024-08-13 16:00 UTC, Vadym-Mazurenko commented on assets/testimonials.js
> +});
fixed

2024-08-13 16:00 UTC, Vadym-Mazurenko commented on sections/testimonials-full-width.liquid
> +          "label": "Staps per day"
fixed

2024-08-13 16:00 UTC, Vadym-Mazurenko commented on sections/testimonials.liquid
> +      "name": "testimonials_video",
fixed

2024-08-13 16:00 UTC, Vadym-Mazurenko commented on sections/testimonials.liquid
> +    calc(100vw - 10rem), 100vw
fixed

2024-08-13 16:01 UTC, Vadym-Mazurenko commented on sections/testimonials.liquid
> +    (min-width: {{ settings.page_width }}px) {{ settings.page_width | minus: 100 }}px, (min-width: 750px)
fixed

2024-08-13 17:50 UTC, alex-wuffes commented on sections/testimonials-full-width.liquid
> +  ]
@Vadym-Mazurenko That's better, but section 1 still looks off. 
<img width="664" alt="image" src="https://github.com/user-attachments/assets/00835022-395e-4ffe-9d3d-5e3f3cd2a1a5">

I suggest adding a proper color schema into the preset

2024-08-13 17:51 UTC, alex-wuffes commented on sections/testimonials.liquid
> +                      {% endif %}
@Vadym-Mazurenko I can still [find](https://tppr.me/2ynvRi) blocks that don't have this attribute

2024-08-13 17:55 UTC, alex-wuffes requested changes
@Vadym-Mazurenko I left a few comments in some of the previous conversations and marked them unresolved

2024-08-15 16:49 UTC, alex-wuffes commented
Duplicate https://github.com/Wuffes/wuffes-OS2.0/pull/13

2024-08-15 16:49 UTC, closed without merging