Main Quiz for OS2.0 version is built
Wuffes/wuffes-OS2.0 pull request #11
Opened 2024-08-11 19:17 UTC by jayveedev

### Asana Task link:

- [Asana Task](https://app.asana.com/0/1206375175000843/1207248759862709/f)

### Demo links

- [Store](https://wuffes.com/pages/quiz?view=quiz&preview_theme_id=130982150279)
- [Editor](https://admin.shopify.com/store/wuffes-store/themes/130982150279/editor?previewPath=%2Fpages%2Fabout-us%3Fview%3Dquiz&section=template--16266049716359__main_quiz_GXBWM3)

### Checklist

- [x] Tested on mobile
- [x] Tested on desktop
- [x] Requested review from QA (if applicable)

- [x] Requested approval from 1 senior dev on Github and in Asana task
- [x] Moved task to "QA" status in Asana

2024-08-12 17:27 UTC, alex-wuffes requested changes

2024-08-12 17:27 UTC, alex-wuffes commented on snippets/quiz-step.liquid
> +            assign grid_class = 'quiz_step__radio_wrap--two_grid'
@jayveedev We have to use "-" as a divider for entity name in [BEM](https://getbem.com/introduction/).
So this has to be "quiz-step__radio-wrap--two-grid

2024-08-12 17:27 UTC, alex-wuffes commented on assets/global.js
> +    this.defaultRedirect = this.getAttribute('data-default-redirect') ?? 'full_price';
@jayveedev much easier with dataset. 
E.g. this.dataset.redirectUrl, this.dataset.redirectUrlPdpSb. 

HTML stays the same. JS automatically converts dashes to camelCase

2024-08-12 17:27 UTC, alex-wuffes commented on sections/main-quiz.liquid
> +        <loading-screen class="quiz_step__loading_screen">
@jayveedev I don't think you should make custom elements out of divs if they don't have a custom JS logic. I'm not sure about my thought, but please check it. Let's discuss on a call after.

2024-08-12 17:27 UTC, alex-wuffes commented on snippets/icon-dogs.liquid
> +{%- case asset -%}
@jayveedev let's not use any liquid like this inside of the icon snippet. In case you want to create a logic like this - have a separate icon for each dog size, and import them in a separate script adding the logic. Or just insert this logic to the quiz liquid file.

2024-08-12 17:27 UTC, alex-wuffes commented on assets/global.js
> +class Quiz extends HTMLElement {
@jayveedev Considering that quiz JS will be needed only on the quiz page - there is no need to add it to the global file. 
Create a separate JS and load it from your quiz section

2024-08-12 17:27 UTC, alex-wuffes commented on snippets/quiz-step.liquid
> +<quiz-step quiz-step-index="{{ step_index }}">
@jayveedev Don't forget about {{ shopify.block_attributes }}

2024-08-13 13:09 UTC, jayveedev commented on snippets/quiz-step.liquid
> +<quiz-step quiz-step-index="{{ step_index }}">
my bad, fixed :)

2024-08-13 17:58 UTC, alex-wuffes approved these changes

2024-08-13 17:58 UTC, merged